//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIATubeHtml5.wsLogs {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="THE_LogAccesos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class THE_LogAccesos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CveLogAccesosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FIATubeHtml5.wsLogs.TDI_EMPL CveEmpleadoField;
        
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DominioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CveLogAccesos {
            get {
                return this.CveLogAccesosField;
            }
            set {
                if ((this.CveLogAccesosField.Equals(value) != true)) {
                    this.CveLogAccesosField = value;
                    this.RaisePropertyChanged("CveLogAccesos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public FIATubeHtml5.wsLogs.TDI_EMPL CveEmpleado {
            get {
                return this.CveEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CveEmpleadoField, value) != true)) {
                    this.CveEmpleadoField = value;
                    this.RaisePropertyChanged("CveEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Modulo {
            get {
                return this.ModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuloField, value) != true)) {
                    this.ModuloField = value;
                    this.RaisePropertyChanged("Modulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dominio {
            get {
                return this.DominioField;
            }
            set {
                if ((object.ReferenceEquals(this.DominioField, value) != true)) {
                    this.DominioField = value;
                    this.RaisePropertyChanged("Dominio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MachineName {
            get {
                return this.MachineNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNameField, value) != true)) {
                    this.MachineNameField = value;
                    this.RaisePropertyChanged("MachineName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DirIP {
            get {
                return this.DirIPField;
            }
            set {
                if ((object.ReferenceEquals(this.DirIPField, value) != true)) {
                    this.DirIPField = value;
                    this.RaisePropertyChanged("DirIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TDI_EMPL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TDI_EMPL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmpleadoLlavePrimariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FIATubeHtml5.wsLogs.TDI_TipoEmpleado EmpleadoTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoUsrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoStatusField;
        
        private int EmpleadoNumeroField;
        
        private int EmpleadoChkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoChkVisibleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmpleadoLlavePrimaria {
            get {
                return this.EmpleadoLlavePrimariaField;
            }
            set {
                if ((this.EmpleadoLlavePrimariaField.Equals(value) != true)) {
                    this.EmpleadoLlavePrimariaField = value;
                    this.RaisePropertyChanged("EmpleadoLlavePrimaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public FIATubeHtml5.wsLogs.TDI_TipoEmpleado EmpleadoTipo {
            get {
                return this.EmpleadoTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoTipoField, value) != true)) {
                    this.EmpleadoTipoField = value;
                    this.RaisePropertyChanged("EmpleadoTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmpleadoNombre {
            get {
                return this.EmpleadoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoNombreField, value) != true)) {
                    this.EmpleadoNombreField = value;
                    this.RaisePropertyChanged("EmpleadoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmpleadoUsr {
            get {
                return this.EmpleadoUsrField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoUsrField, value) != true)) {
                    this.EmpleadoUsrField = value;
                    this.RaisePropertyChanged("EmpleadoUsr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EmpleadoStatus {
            get {
                return this.EmpleadoStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoStatusField, value) != true)) {
                    this.EmpleadoStatusField = value;
                    this.RaisePropertyChanged("EmpleadoStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int EmpleadoNumero {
            get {
                return this.EmpleadoNumeroField;
            }
            set {
                if ((this.EmpleadoNumeroField.Equals(value) != true)) {
                    this.EmpleadoNumeroField = value;
                    this.RaisePropertyChanged("EmpleadoNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int EmpleadoChk {
            get {
                return this.EmpleadoChkField;
            }
            set {
                if ((this.EmpleadoChkField.Equals(value) != true)) {
                    this.EmpleadoChkField = value;
                    this.RaisePropertyChanged("EmpleadoChk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string EmpleadoChkVisible {
            get {
                return this.EmpleadoChkVisibleField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoChkVisibleField, value) != true)) {
                    this.EmpleadoChkVisibleField = value;
                    this.RaisePropertyChanged("EmpleadoChkVisible");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TDI_TipoEmpleado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TDI_TipoEmpleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmpleadoTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionTipoEmpleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmpleadoTipo {
            get {
                return this.EmpleadoTipoField;
            }
            set {
                if ((this.EmpleadoTipoField.Equals(value) != true)) {
                    this.EmpleadoTipoField = value;
                    this.RaisePropertyChanged("EmpleadoTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DescripcionTipoEmpleado {
            get {
                return this.DescripcionTipoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionTipoEmpleadoField, value) != true)) {
                    this.DescripcionTipoEmpleadoField = value;
                    this.RaisePropertyChanged("DescripcionTipoEmpleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsLogs.WebService_ManejadorLogsSoap")]
    public interface WebService_ManejadorLogsSoap {
        
        // CODEGEN: Generating message contract since element name LogAccesos from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLogAccesos", ReplyAction="*")]
        FIATubeHtml5.wsLogs.GuardarLogAccesosResponse GuardarLogAccesos(FIATubeHtml5.wsLogs.GuardarLogAccesosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogAccesosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLogAccesos", Namespace="http://tempuri.org/", Order=0)]
        public FIATubeHtml5.wsLogs.GuardarLogAccesosRequestBody Body;
        
        public GuardarLogAccesosRequest() {
        }
        
        public GuardarLogAccesosRequest(FIATubeHtml5.wsLogs.GuardarLogAccesosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogAccesosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FIATubeHtml5.wsLogs.THE_LogAccesos LogAccesos;
        
        public GuardarLogAccesosRequestBody() {
        }
        
        public GuardarLogAccesosRequestBody(FIATubeHtml5.wsLogs.THE_LogAccesos LogAccesos) {
            this.LogAccesos = LogAccesos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogAccesosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLogAccesosResponse", Namespace="http://tempuri.org/", Order=0)]
        public FIATubeHtml5.wsLogs.GuardarLogAccesosResponseBody Body;
        
        public GuardarLogAccesosResponse() {
        }
        
        public GuardarLogAccesosResponse(FIATubeHtml5.wsLogs.GuardarLogAccesosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogAccesosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GuardarLogAccesosResult;
        
        public GuardarLogAccesosResponseBody() {
        }
        
        public GuardarLogAccesosResponseBody(bool GuardarLogAccesosResult) {
            this.GuardarLogAccesosResult = GuardarLogAccesosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_ManejadorLogsSoapChannel : FIATubeHtml5.wsLogs.WebService_ManejadorLogsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_ManejadorLogsSoapClient : System.ServiceModel.ClientBase<FIATubeHtml5.wsLogs.WebService_ManejadorLogsSoap>, FIATubeHtml5.wsLogs.WebService_ManejadorLogsSoap {
        
        public WebService_ManejadorLogsSoapClient() {
        }
        
        public WebService_ManejadorLogsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_ManejadorLogsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ManejadorLogsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ManejadorLogsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FIATubeHtml5.wsLogs.GuardarLogAccesosResponse FIATubeHtml5.wsLogs.WebService_ManejadorLogsSoap.GuardarLogAccesos(FIATubeHtml5.wsLogs.GuardarLogAccesosRequest request) {
            return base.Channel.GuardarLogAccesos(request);
        }
        
        public bool GuardarLogAccesos(FIATubeHtml5.wsLogs.THE_LogAccesos LogAccesos) {
            FIATubeHtml5.wsLogs.GuardarLogAccesosRequest inValue = new FIATubeHtml5.wsLogs.GuardarLogAccesosRequest();
            inValue.Body = new FIATubeHtml5.wsLogs.GuardarLogAccesosRequestBody();
            inValue.Body.LogAccesos = LogAccesos;
            FIATubeHtml5.wsLogs.GuardarLogAccesosResponse retVal = ((FIATubeHtml5.wsLogs.WebService_ManejadorLogsSoap)(this)).GuardarLogAccesos(inValue);
            return retVal.Body.GuardarLogAccesosResult;
        }
    }
}
