//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIATubeHtml5.wsManejadorErrores {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="THE_LogErrores", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class THE_LogErrores : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CveLogErroresField;
        
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FIATubeHtml5.wsManejadorErrores.TDI_EMPL CveEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PantallaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DominioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CveLogErrores {
            get {
                return this.CveLogErroresField;
            }
            set {
                if ((this.CveLogErroresField.Equals(value) != true)) {
                    this.CveLogErroresField = value;
                    this.RaisePropertyChanged("CveLogErrores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public FIATubeHtml5.wsManejadorErrores.TDI_EMPL CveEmpleado {
            get {
                return this.CveEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CveEmpleadoField, value) != true)) {
                    this.CveEmpleadoField = value;
                    this.RaisePropertyChanged("CveEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Pantalla {
            get {
                return this.PantallaField;
            }
            set {
                if ((object.ReferenceEquals(this.PantallaField, value) != true)) {
                    this.PantallaField = value;
                    this.RaisePropertyChanged("Pantalla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Dominio {
            get {
                return this.DominioField;
            }
            set {
                if ((object.ReferenceEquals(this.DominioField, value) != true)) {
                    this.DominioField = value;
                    this.RaisePropertyChanged("Dominio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MachineName {
            get {
                return this.MachineNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNameField, value) != true)) {
                    this.MachineNameField = value;
                    this.RaisePropertyChanged("MachineName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DirIP {
            get {
                return this.DirIPField;
            }
            set {
                if ((object.ReferenceEquals(this.DirIPField, value) != true)) {
                    this.DirIPField = value;
                    this.RaisePropertyChanged("DirIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TDI_EMPL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TDI_EMPL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmpleadoLlavePrimariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FIATubeHtml5.wsManejadorErrores.TDI_TipoEmpleado EmpleadoTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoUsrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoStatusField;
        
        private int EmpleadoNumeroField;
        
        private int EmpleadoChkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoChkVisibleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmpleadoLlavePrimaria {
            get {
                return this.EmpleadoLlavePrimariaField;
            }
            set {
                if ((this.EmpleadoLlavePrimariaField.Equals(value) != true)) {
                    this.EmpleadoLlavePrimariaField = value;
                    this.RaisePropertyChanged("EmpleadoLlavePrimaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public FIATubeHtml5.wsManejadorErrores.TDI_TipoEmpleado EmpleadoTipo {
            get {
                return this.EmpleadoTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoTipoField, value) != true)) {
                    this.EmpleadoTipoField = value;
                    this.RaisePropertyChanged("EmpleadoTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmpleadoNombre {
            get {
                return this.EmpleadoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoNombreField, value) != true)) {
                    this.EmpleadoNombreField = value;
                    this.RaisePropertyChanged("EmpleadoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmpleadoUsr {
            get {
                return this.EmpleadoUsrField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoUsrField, value) != true)) {
                    this.EmpleadoUsrField = value;
                    this.RaisePropertyChanged("EmpleadoUsr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EmpleadoStatus {
            get {
                return this.EmpleadoStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoStatusField, value) != true)) {
                    this.EmpleadoStatusField = value;
                    this.RaisePropertyChanged("EmpleadoStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int EmpleadoNumero {
            get {
                return this.EmpleadoNumeroField;
            }
            set {
                if ((this.EmpleadoNumeroField.Equals(value) != true)) {
                    this.EmpleadoNumeroField = value;
                    this.RaisePropertyChanged("EmpleadoNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int EmpleadoChk {
            get {
                return this.EmpleadoChkField;
            }
            set {
                if ((this.EmpleadoChkField.Equals(value) != true)) {
                    this.EmpleadoChkField = value;
                    this.RaisePropertyChanged("EmpleadoChk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string EmpleadoChkVisible {
            get {
                return this.EmpleadoChkVisibleField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoChkVisibleField, value) != true)) {
                    this.EmpleadoChkVisibleField = value;
                    this.RaisePropertyChanged("EmpleadoChkVisible");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TDI_TipoEmpleado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TDI_TipoEmpleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmpleadoTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionTipoEmpleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmpleadoTipo {
            get {
                return this.EmpleadoTipoField;
            }
            set {
                if ((this.EmpleadoTipoField.Equals(value) != true)) {
                    this.EmpleadoTipoField = value;
                    this.RaisePropertyChanged("EmpleadoTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DescripcionTipoEmpleado {
            get {
                return this.DescripcionTipoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionTipoEmpleadoField, value) != true)) {
                    this.DescripcionTipoEmpleadoField = value;
                    this.RaisePropertyChanged("DescripcionTipoEmpleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsManejadorErrores.WebService_ManejadorErroresSoap")]
    public interface WebService_ManejadorErroresSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoWork", ReplyAction="*")]
        void DoWork();
        
        // CODEGEN: Generating message contract since element name LogError from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLogError", ReplyAction="*")]
        FIATubeHtml5.wsManejadorErrores.GuardarLogErrorResponse GuardarLogError(FIATubeHtml5.wsManejadorErrores.GuardarLogErrorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLogError", Namespace="http://tempuri.org/", Order=0)]
        public FIATubeHtml5.wsManejadorErrores.GuardarLogErrorRequestBody Body;
        
        public GuardarLogErrorRequest() {
        }
        
        public GuardarLogErrorRequest(FIATubeHtml5.wsManejadorErrores.GuardarLogErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FIATubeHtml5.wsManejadorErrores.THE_LogErrores LogError;
        
        public GuardarLogErrorRequestBody() {
        }
        
        public GuardarLogErrorRequestBody(FIATubeHtml5.wsManejadorErrores.THE_LogErrores LogError) {
            this.LogError = LogError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLogErrorResponse", Namespace="http://tempuri.org/", Order=0)]
        public FIATubeHtml5.wsManejadorErrores.GuardarLogErrorResponseBody Body;
        
        public GuardarLogErrorResponse() {
        }
        
        public GuardarLogErrorResponse(FIATubeHtml5.wsManejadorErrores.GuardarLogErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GuardarLogErrorResult;
        
        public GuardarLogErrorResponseBody() {
        }
        
        public GuardarLogErrorResponseBody(bool GuardarLogErrorResult) {
            this.GuardarLogErrorResult = GuardarLogErrorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_ManejadorErroresSoapChannel : FIATubeHtml5.wsManejadorErrores.WebService_ManejadorErroresSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_ManejadorErroresSoapClient : System.ServiceModel.ClientBase<FIATubeHtml5.wsManejadorErrores.WebService_ManejadorErroresSoap>, FIATubeHtml5.wsManejadorErrores.WebService_ManejadorErroresSoap {
        
        public WebService_ManejadorErroresSoapClient() {
        }
        
        public WebService_ManejadorErroresSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_ManejadorErroresSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ManejadorErroresSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ManejadorErroresSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FIATubeHtml5.wsManejadorErrores.GuardarLogErrorResponse FIATubeHtml5.wsManejadorErrores.WebService_ManejadorErroresSoap.GuardarLogError(FIATubeHtml5.wsManejadorErrores.GuardarLogErrorRequest request) {
            return base.Channel.GuardarLogError(request);
        }
        
        public bool GuardarLogError(FIATubeHtml5.wsManejadorErrores.THE_LogErrores LogError) {
            FIATubeHtml5.wsManejadorErrores.GuardarLogErrorRequest inValue = new FIATubeHtml5.wsManejadorErrores.GuardarLogErrorRequest();
            inValue.Body = new FIATubeHtml5.wsManejadorErrores.GuardarLogErrorRequestBody();
            inValue.Body.LogError = LogError;
            FIATubeHtml5.wsManejadorErrores.GuardarLogErrorResponse retVal = ((FIATubeHtml5.wsManejadorErrores.WebService_ManejadorErroresSoap)(this)).GuardarLogError(inValue);
            return retVal.Body.GuardarLogErrorResult;
        }
    }
}
